a = int(input("Enter the first number = "))
b = int(input("Enter the second number = "))
print("Addition = ",(a+b))
print("Substraction = ",(a-b))
print("Multiplicaton = ",(a*b))
print("Division = ",(a/b))
