l = int(input("Enter the length of Cuboid = "))
b = int(input("Enter the breadth of Cuboid = "))
h = int(input("Enter the height of Cuboid = "))
print("Area of Cuboid = ",int((l*b*h)))
print("Perimeter of Cuboid = ",int((4*(l+b+h))))